"""create files table

Revision ID: baa682a3ce1e
Revises: 9db412c50f26
Create Date: 2026-06-15 13:01:36.224953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baa682a3ce1e'
down_revision: Union[str, Sequence[str], None] = '9db412c50f26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('path_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('full_path', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=False),
    sa.Column('ocr_applied', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('file_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('file_modified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), server_default='discovered', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['path_id'], ['paths.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('full_path')
    )
    op.create_index(op.f('ix_files_file_hash'), 'files', ['file_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_files_file_hash'), table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###
